---
title: "Cropland and Climate"
bibliography: project4.bib
author:
  - name: Meucci Ilunga & Sara Hunsberger & Fernanda Montoya & Meklit Yimenu
    email: milunga2@jh.edu & shunsbe2@jh.edu & fmontoy1@jh.edu & myimenu1@jh.edu
    jhedid: milunga2 & shunsbe2 & fmontoy & myimenu1
format: pdf
editor: visual
---

# Research Question and Importance

How do variations in climate data (temperature, precipitation, and extreme weather events) affect cropland health and productivity over time, and can predictive models help identify future trends and risks?

# Already Existing Work

There has been research done on the impact of climate change on vegetation in the United States, for example the article "Impacts of global change on peak vegetation growth and its timing in terrestrial ecosystems of the continental US" by Ying Liu et.al describes an analysis using similar factors that we will be looking at including how the Normalized Difference Vegetation Index (NDVI) changes with differences in temperature, precipitation and cloud cover. But this research was done on all vegetation in the United States, where we are more interested in how climate change impacts cropland specifically. This study found that precipitation had the largest impact on NDVI, which tells us that precipitation will be a good metric to look at for our analysis. [@LIU2021103657]

In terms of looking at climate change and cropland specifically, the paper "Climate change and adaptation in agriculture: Evidence from US cropping patterns" by Xiaomeng Cui talks about climate change’s effect on the types of crops being planted; for example in the US, soybean and corn production has increased, and this paper says that climate change has contributed to that increase. This means that in our analysis we can also possibly examine shifts in crops along with changes to their NDVI and other metrics of crop health. [@CUI2020102306]

# Outline of Work

The goal of our project is to determine how climate change impacts cropland in the United states, we will use three data sets to examine this question. The first is a dataset that will map out where cropland is in the United states. We will then combine this data with a dataset that gives us information on how the vegetation is doing across the US. This means we will use the vegetation data from the areas designated as croplands from the cropland data. Finally we will retrieve climate measures for those areas over time and compare the vegetation indexes to determine how the crops are doing to the climate measures. Following this data extraction and processing, we will answer our primary research question with a data analysis conducted in R and deploy the analysis formally on a Quarto website.

# Program Paradigms

We will use the following program paradigms: Functional programming (R), Object oriented programming (Python for accessing data through API), explore parallel programming to deal with size of data set.

# Packages and Software

For the packages we can use the program R, use Python to get data from the earth engine, rgee (to work with API data through R).
We then will use the following packages to process the crop land data QGIS/ARCGis and Geopandas. 

# Data Collection

Data collection for this project will involve three primary data sources which we will then combine for our analysis. The three data sources are explored below:

**Crop land data:** We will use one of the two following sources from Earth Engine to retrieve data on where cropland is in the United States. The first source is the USDA NASS Cropland Data Layers ([source](https://developers.google.com/earth-engine/datasets/catalog/USDA_NASS_CDL) . The second source is global food support analysis data ([source](https://developers.google.com/earth-engine/datasets/catalog/USGS_GFSAD1000_V1). We are not sure which data will be best to use when we actually pull the data so we will explore both. Both data sets are considered public domain and we are able to retrieve both data sets with API calls from Earth Engine.

**Vegetation data:** We will use MODIS data also retrieved with an API call from Earth Engine which has no restrictions on use ([source](https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD13A1)). In this data we will use the Normalized Difference Vegetation Index, Enhanced Vegetation Index and Terra MODIS Vegetation Continuous Fields as metrics to understand how well the vegetation is doing in different areas.

**Climate data:** We will use the PRISM Daily Spatial Climate Dataset from Earth Engine which has no restrictions on use
([source](https://developers.google.com/earth-engine/datasets/catalog/OREGONSTATE_PRISM_AN81d)). This data includes data on temperature and precipitation for different areas in the US.

# Product

Our final product will be a deployed Quarto website that walks through the research question and analysis, and summarizes the final project findings. We plan to include details on how the data was sourced and processed, along with visualizations and specific data analysis models used.

# Timeline

The tentative project timeline is as follows:

Week 1 (11/18): Meeting with Wenxuan to assess feasibility of project and make adjustments to project goals as needed. Data extraction and processing. 
eek 2 (11/25): Data cleaning and data analysis. Start of website deployment 
Week 3 (12/2): Continuation of data analysis. Implementation of data visualizations. Continuation of website development. 
Week 4 (12/9): Finalization of data analysis. Finalization and submission of project presentation. Group presentation to course. Changes to analysis following presentation feedback. 
Week 5 (12/16): Final project report finalization and submission. Group evaluation submission.

# Task Split

We will split up the work in the following manner with everyone collaborating on problems that arise. 

Meucci: Data extraction and processing, final presentation and report contributions, review of website and quality of analysis. 
Sara: Data analysis & visualization, final presentation and report contributions, review of website and quality of analysis. 
Fernanda: Data analysis & visualization, final presentation and report contributions, review of website and quality of analysis.
Meklit: Website creation, final presentation and report contributions, review of website and quality of analysis.
